[package]
name = "pretty_dtoa"
version = "0.1.0"
authors = ["Matthew Torrence <matt@torrencefamily.net>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"
rand = "0.7.3"

[[bench]]
name = "dtoa_benchmark"
harness = false

[dependencies]
ryu = { git = "https://github.com/torrencem/ryu" }

