[package]
name = "display_float"
version = "0.1.0"
authors = ["Matthew Torrence <matt@torrencefamily.net>"]
edition = "2018"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "dtoa_benchmark"
harness = false

[dependencies]
